# array

In [3]:
import numpy as np
array = np.array([1,3,4])
array

array([1, 3, 4])

In [5]:
print(array/2)

[0.5 1.5 2. ]


In [7]:
# if you have a long sequence of items  consider using an array 
# this structure offers more efficient data storage
# if you have numerical operations with your combination of items use array. data analytics and data science rely on arrays.

In [41]:
b =  np.array([1,3,4])
print(b)
print()
c = np.array([[1,4,5],[3,6,5]])
print(c)
print()
d  = np.array([[[1,2,3],[3,4,5],[6,7,8],[23,45,67],[34,56,76]]])
print(d)
print()

[1 3 4]

[[1 4 5]
 [3 6 5]]

[[[ 1  2  3]
  [ 3  4  5]
  [ 6  7  8]
  [23 45 67]
  [34 56 76]]]



In [42]:
# function to print the dimensions
# print(array_name.ndim)


In [43]:
b.shape, c.shape,d.shape

((3,), (2, 3), (1, 5, 3))

In [44]:
print(c)
print()

[[1 4 5]
 [3 6 5]]



In [45]:
ak = c.reshape(3,2)
print(ak)

[[1 4]
 [5 3]
 [6 5]]


In [46]:
d

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [23, 45, 67],
        [34, 56, 76]]])

In [47]:
print(d[0][4][1])

56


In [48]:
c

array([[1, 4, 5],
       [3, 6, 5]])

In [49]:
c[0:2,1:3]

array([[4, 5],
       [6, 5]])

In [50]:
c[0:2,1:2]

array([[4],
       [6]])

In [51]:
c[0:1,1:3]

array([[4, 5]])

In [53]:
a = np.zeros((2,2),dtype='int')
print(a)
print()

[[0 0]
 [0 0]]



In [56]:
f = np.ones((1,2),dtype='int')
print(f)
print()

[[1 1]]



In [70]:
n =np.full((2,2),9) 
print(n)
print()

[[9 9]
 [9 9]]



In [71]:
y = np.eye(3)
print(y)
print()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [75]:
# creates an array filled with random variables
e = np.random.random((2,4))
e

array([[0.9649236 , 0.0857113 , 0.57509207, 0.99574827],
       [0.68632381, 0.59931893, 0.41558664, 0.77468068]])

In [83]:
r = np.array([[1,2,3,45],[56,45,67,88],[55,34,89,443]])
r 

array([[  1,   2,   3,  45],
       [ 56,  45,  67,  88],
       [ 55,  34,  89, 443]])

In [85]:
r[1,3]=22
r

array([[  1,   2,   3,  45],
       [ 56,  45,  22,  22],
       [ 55,  34,  89, 443]])

In [88]:
np.arange(1,5)

array([1, 2, 3, 4])

In [91]:
np.arange(45,0,-2)

array([45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21, 19, 17, 15, 13,
       11,  9,  7,  5,  3,  1])

In [95]:
h = np.arange(12).reshape(4,3)
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [96]:
y = np.linspace(1,20,5) # end range is inclusive
y

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [98]:
np.repeat("$",7)


array(['$', '$', '$', '$', '$', '$', '$'], dtype='<U1')

In [106]:
np.random.randint(4,10)

4

In [111]:
x = np.array([[111,2],[3,4]])
print(x)
print()
y = np.array([[5,16],[17,18]])
print(y)
print()
print(np.sum(x))
print()
print(np.sum(x,axis=0))
print()
print(np.sum(x,axis=1))



[[111   2]
 [  3   4]]

[[ 5 16]
 [17 18]]

120

[114   6]

[113   7]
[[11]
 [ 1]]
[ 80 306]


In [112]:
y

array([[ 5, 16],
       [17, 18]])

In [113]:
print(np.diff(y,axis= 0))

[[12  2]]


In [114]:
print(np.prod(y,axis= 1))

[ 80 306]


# PANDAS

In [115]:
import pandas as pd

In [116]:
data = pd.Series([123,456,567])
data

0    123
1    456
2    567
dtype: int64

In [117]:
# acess with index
data[0]

123

In [119]:
d = pd.Series([420,"Akash nair",15],index=["number","Name","Class"])
d

number           420
Name      Akash nair
Class             15
dtype: object

In [122]:
#access with index
d['Name']

'Akash nair'

In [123]:
cal = {"day1":22,"day2":34,"day3":55}


In [130]:
s = pd.Series(cal)
s

day1    22
day2    34
day3    55
dtype: int64

# DATAFRAME

In [132]:
a = ["Akash","Mary","Tina","Valentina"]
df = pd.DataFrame(a,columns = ["Names"])
df

Names
0      Akash
1       Mary
2       Tina
3  Valentina

In [134]:
b = [["akash",25],["Tina",24],["gillu",5],["Billu",1]]
df1 = pd.DataFrame(b,columns=["Names","Age"])
df1


Names  Age
0  akash   25
1   Tina   24
2  gillu    5
3  Billu    1

In [136]:
c = {"ID":[101,102,103],"DEPARTMENT":["BSC","MSC","MCA"]}
df3 = pd.DataFrame(c)
df3

ID DEPARTMENT
0  101        BSC
1  102        MSC
2  103        MCA